<?php
// $Id: xoops_version.php,v 1.10 2004/12/26 19:12:13 onokazu Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

$modversion['name'] = _MI_POLLS_NAME;
$modversion['version'] = 1.31;
$modversion['description'] = _MI_POLLS_DESC;
$modversion['author'] = "GibaPhp";
$modversion['author_website_name'] = "";
$modversion['author_email'] = "gibaphp.xoopstotal@gmail.com";
$modversion['status_version'] = "1.31";
$modversion['status'] = "RC 1";
$modversion['credits'] = "Code base in Original Mod XoopsPoll by Kazumi Ono";
$modversion['help'] = "xicpoll.html";
$modversion['license'] = "GNU General Public License (GPL) see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/xicpoll_slogo.png";
$modversion['dirname'] = _MI_POLLS_DIRNAME;

$modversion['warning'] = "For XOOPERS *, Xoops, EXM, XoopsCube, ImpressCMS ";

$modversion['demo_site_url'] = "";
$modversion['demo_site_name'] = "";
$modversion['support_site_url'] = " ";
$modversion['support_site_name'] = "Team Xic";
$modversion['submit_feature'] = " ";
$modversion['submit_bug'] = " ";


// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
$modversion['sqlfile']['pdo_mysql'] = "sql/mysql.sql";


// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "xicpoll_option";
$modversion['tables'][1] = "xicpoll_desc";
$modversion['tables'][2] = "xicpoll_log";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

//config - Nazar
$modversion['config'][0] = array(
  'name'      => "limit_by_ip" ,
  'title'     => '_MI_POLL_LIMITBYIP' ,
  'description' => '_MI_POLL_LIMITBYIPD' ,
  'formtype'    => 'yesno' ,
  'valuetype'   => 'int' ,
  'default'   => '1' ,
  'options'   => array()
) ;

//config - Nazar
$modversion['config'][1] = array(
  'name'      => "limit_by_uid" ,
  'title'     => '_MI_POLL_LIMITBYUID' ,
  'description' => '_MI_POLL_LIMITBYUIDD' ,
  'formtype'    => 'yesno' ,
  'valuetype'   => 'int' ,
  'default'   => '0' ,
  'options'   => array()
) ;

// config - wellwine
$modversion['config'][2] = array(
  'name'        => "lookuphost" ,
  'title'       => "_MI_POLLS_LOOKUPHOST" ,
  'description' => "_MI_POLLS_LOOKUPHOSTDESC" ,
  'formtype'    => "yesno" ,
  'valuetype'   => "int" ,
  'default'     => '0' ,
  'options'   => array()
) ;


$modversion['templates'][1]['file'] = 'xicpoll_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'xicpoll_view.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'xicpoll_results.html';
$modversion['templates'][3]['description'] = '';

//Blocks
$modversion['blocks'][1]['file'] = "xicpoll.php";
$modversion['blocks'][1]['name'] = _MI_POLLS_BNAME1;
$modversion['blocks'][1]['description'] = "Shows unlimited number of polls/surveys";
$modversion['blocks'][1]['show_func'] = "b_xicpoll_show";
$modversion['blocks'][1]['options'] = "0|1|1|1|0"; //GibaPhp - option default module normal.
$modversion['blocks'][1]['edit_func'] = "b_xicpoll_edit";
$modversion['blocks'][1]['template'] = 'xicpoll_block_poll.html';

// 2
$modversion['blocks'][2]['file'] = "xicpoll.php";
$modversion['blocks'][2]['name'] = _MI_POLLS_BNAME_02;
$modversion['blocks'][2]['description'] = _MI_POLLS_BDESC_02;
$modversion['blocks'][2]['show_func'] = "b_xicpoll_show";
$modversion['blocks'][2]['options'] = "2|1|1|1|0"; //GibaPhp - option extra 2 module poll new.
$modversion['blocks'][2]['edit_func'] = "b_xicpoll_edit";
$modversion['blocks'][2]['template'] = 'xicpoll_block_poll_02.html';


// 3
$modversion['blocks'][3]['file'] = "xicpoll.php";
$modversion['blocks'][3]['name'] = _MI_POLLS_BNAME_03;
$modversion['blocks'][3]['description'] = _MI_POLLS_BDESC_03;
$modversion['blocks'][3]['show_func'] = "b_xicpoll_show";
$modversion['blocks'][3]['options'] = "3|1|1|1|0"; //GibaPhp - option extra 3 module poll new.
$modversion['blocks'][3]['edit_func'] = "b_xicpoll_edit";
$modversion['blocks'][3]['template'] = 'xicpoll_block_poll_03.html';

// 4
$modversion['blocks'][4]['file'] = "xicpoll.php";
$modversion['blocks'][4]['name'] = _MI_POLLS_BNAME_04;
$modversion['blocks'][4]['description'] = _MI_POLLS_BDESC_04;
$modversion['blocks'][4]['show_func'] = "b_xicpoll_show";
$modversion['blocks'][4]['options'] = "4|1|1|1|0"; //GibaPhp - option extra 4 module poll new.
$modversion['blocks'][4]['edit_func'] = "b_xicpoll_edit";
$modversion['blocks'][4]['template'] = 'xicpoll_block_poll_04.html';

// Menu
$modversion['hasMain'] = 1;

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'pollresults.php';
$modversion['comments']['itemName'] = 'poll_id';
?>
